In [1]:
from selenium import webdriver
import time
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd
from urllib.parse import urljoin
import re
import time

In [2]:
driver =  webdriver.Chrome(executable_path = 'D:\workspace\chromedriver.exe' )

driver.get('https://ev.or.kr/evmonitor')
#time.sleep(5)

In [18]:
count=0
if count==0:
    tmp_len=0
    create_date=[]

In [19]:
sid = []

In [20]:
for k in range(2,19):
    driver.find_element_by_css_selector('#F_SI_DO1')
    driver.implicitly_wait(5)
    driver.find_element_by_css_selector('#F_SI_DO1 > option:nth-child(%s)'%k).click()
    #time.sleep(3)
    driver.find_element_by_css_selector('#statList')
    driver.implicitly_wait(30)
    html = driver.page_source
    soup = BeautifulSoup(html, 'html.parser')
    
    a = soup.find_all('div',class_='fw_path')
    for link in a:
        temp = str(link['sid'])
        sid.append(temp)

In [21]:
len(sid)

2495

In [22]:
tmp_len2 = len(sid)-tmp_len
    
if tmp_len != len(sid):
    tmp_len2 = len(sid)-tmp_len
for i in range (0,tmp_len2):
    i = time.ctime()
    create_date.append(i)
    
tmp_len = len(sid)
count+=1

In [23]:
print(len(create_date))

2495

In [24]:
#충전소_딕셔너리
c_station = {'name':[], 'u_time':[], 'agency': [], 'city':[], 'gu':[], 'add':[],'phone':[], 'fee':[],'etc':[]}
#충전기_딕셔너리
charger = {'c_name':[], 'typ':[], 'charge':[], 'using':[], 'amount':[]}

In [25]:
count2=0
if count2==0:
    tmp_len_2=0
    c_create_date=[]

In [26]:
for i in sid[0:40]:
    url_base = 'https://www.ev.or.kr/portal/monitor/evminfo?sid='
    url = url_base+str(i)
    html = urlopen(url)
    soup = BeautifulSoup(html, 'html.parser')
    
    for tmp_using in soup.find_all(class_='table_01'):
        n_tmp = soup.find_all('h2')
        c_station['name'].append(n_tmp[0].get_text())

        t_tmp = soup.find_all('em')
        c_station['u_time'].append(t_tmp[0].get_text())

        info_tmp = soup.find_all(class_='table_02')
        dinfo = info_tmp[0].find_all('td')
        c_station['add'].append(dinfo[0].get_text())
        c_station['agency'].append(dinfo[1].get_text())
        c_station['phone'].append(dinfo[2].get_text())
    
        tmp_fee = dinfo[3].get_text()
        tmp_fee = re.sub('&nbsp; | &nbsp; |\n|\t|\r|', '', tmp_fee)
        c_station['fee'].append(tmp_fee)
        
            
        tmp_etc = dinfo[5].get_text()
        tmp_etc = re.sub('&nbsp; | &nbsp; |\n|\t|\r|', '', tmp_etc)
        c_station['etc'].append(tmp_etc)
        
        city_tmp = dinfo[0].get_text().split(' ')
        city_tmp = city_tmp[0]
        gu_tmp = dinfo[0].get_text().split(' ')
        gu_tmp = gu_tmp[1]
        c_station['gu'].append(gu_tmp)
        c_station['city'].append(city_tmp)
        
        if len(tmp_using)<=5:
            
            n_tmp = soup.find_all('h2')
            charger['c_name'].append(n_tmp[0].get_text())

            ty_tmp = soup.find_all('dd')
            charger['typ'].append(ty_tmp[0].get_text())
            
            tmp_amount = dinfo[4].get_text()
            
            tmp_amount = re.findall('\d+', tmp_amount)
            charger['amount'].append(tmp_amount[0])
            
            for u_tmp in soup.find_all(class_='td3'):
                tmp = re.sub('\n', '', u_tmp.get_text())
                charger['using'].append(tmp)
            
    
            td2 = soup.find_all(class_='td2')
            for te in td2[0:]:
                test=[]
                for a in te.find_all('span'):
                    if a.get_text()=='사용가능':
                        break
                    elif a.get_text()=='사용중':
                        break
                    elif a.get_text()=='사용불가':
                        break
                    elif a.get_text()==' ':
                        break
                    elif len(a.get_text())<6:
                        tmp=[]
                        tmp.append(a.get_text())
                        #print(tmp)
                        test+=tmp
                test= str("+".join(test))
                charger['charge'].append(test)
                if test!=None:
                    break

                
            
        elif len(tmp_using)<=7:
            tmp_using = soup.find_all(class_='ev_type t03')
                #print(tmp_using)
            for te in tmp_using[0:]:
                    #print(te)
                for a in te.find_all('span'):
                    if a.get_text()==' ':
                        break
                    elif len(a.get_text())<6:
                        charger['charge'].append(a.get_text())

                        n_tmp = soup.find_all('h2')
                        charger['c_name'].append(n_tmp[0].get_text())

                        ty_tmp = soup.find_all('dd')
                        charger['typ'].append(ty_tmp[0].get_text())

                        tmp_amount = dinfo[4].get_text()
            
                        tmp_amount = re.findall('\d+', tmp_amount) #숫자만 추출
                        charger['amount'].append(tmp_amount[0])

                        for u_tmp in soup.find_all(class_='td3'):
                            tmp = re.sub('\n', '', u_tmp.get_text())
                            charger['using'].append(tmp)
                            break

In [28]:
import time

In [29]:
tmp_len3 = len(charger['c_name'])-tmp_len_2
    
if tmp_len3 != len(charger['c_name']):
    tmp_len3 = len(charger['c_name'])-tmp_len_2
for i in range (0,tmp_len3):
    i = time.ctime()
    c_create_date.append(i)

tmp_len3 = len(charger['c_name'])
count2+=1

In [30]:
print(len(c_create_date), len(charger['c_name']))

45 45

In [31]:
len(c_station['name'])

40

In [32]:
df = pd.DataFrame({'이름':c_station['name'], '사용가능시간':c_station['u_time'], '운영기관':c_station['agency'],'도시':c_station['city'], '구': c_station['gu'],'도로명주소': c_station['add'],'연락처': c_station['phone'],'충전요금': c_station['fee'], '참고사항': c_station['etc']})
df

,이름,사용가능시간,운영기관,도시,구,도로명주소,연락처,충전요금,참고사항
0,DMC 산학협력연구센터,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,마포구,서울특별시 마포구 매봉산로 37,1661-9408,유료,10분/500원
1,Park M (주차복합빌딩),24시간 이용가능,환경부(한국자동차환경협회),서울특별시,마포구,서울특별시 마포구 매봉산로 80,1661-9408,무료,"최초30분 1500원, 10분당 500원 주민센터이용 50% 할인"
2,SETEC,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 남부순환로3104,1661-9408,유료,"충전차량에한하여 1시간무료 10분당500월 일주차15,000원"
3,sh서울주택도시공사,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 개포로 621,1661-9408,유료,없음
4,가로공원로 지하공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강서구,서울특별시 강서구 가로공원로 189 지하주차장 05,1661-9408,유료,주차요금 별도
5,가양레포츠센터,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강서구,서울특별시 강서구 양천로61길 101,1661-9408,유료,없음
6,가오리 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강북구,서울특별시 강북구 삼양로107길 30,1661-9408,유료,5분/150원 친환경차 50% 감면
7,강남구청 삼성로 별관 부설 주차장,09:00~18:00,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 삼성로 628,1661-9408,무료,"5분당 300원, 주말 무료"
8,강남치매지원센터 공영노외주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 선릉로108길 27,1661-9408,무료,5분당400원
9,강동구청,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강동구,서울특별시 강동구 성내로 25,1661-9408,유료,5분 250원 친환경차 50% 감면
10,강변 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,성동구,서울특별시 성동구 둘레길 47-5,1661-9408,무료,5분당 100원 저공해차량 50% 할인
11,강서구민올림픽체육센터,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강서구,서울특별시 강서구 화곡로65길62,1661-9408,유료,없음
12,개봉1동 주민센터 옆 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,구로구,서울특별시 구로구 개봉동 134-8,1661-9408,유료,1시간무료 /구매금액별 50%감면 친환경차 50% 감면
13,개포동공원 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,"서울특별시 강남구 개포로 509 , 지하주차장 1층 8구역(개포동 183-2)",1661-9408,유료,주차비 10분 200원(친환경차 50% 감면)
14,거여동공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,송파구,서울특별시 송파구 오금로68길8,1661-9408,유료,없음
15,곰달래공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,양천구,서울특별시 양천구 곰달래로10길 4,1661-9408,무료,5분당 50원
16,곰달래문화복지센터 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강서구,서울특별시 강서구 강서로5길 50 지상주차장,1661-9408,유료,주차요금 별도
17,공덕1-1공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,마포구,서울특별시 마포구 효창목길 31 옥상,1661-9408,유료,주차요금 별도
18,구로리공원 앞(공중전화부스),24시간 이용가능,환경부(한국자동차환경협회),서울특별시,구로구,서울특별시 구로구 구로동 136-14 (구로동 136-14),1661-9408,유료,없음
19,구룡공원 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,서초구,서울특별시 서초구 양재동 301-6,1661-9408,무료,10분당 300원 저공해차량 50% 할인
20,구민회관,09:00~18:00 이후 무료,환경부(한국자동차환경협회),서울특별시,송파구,서울특별시 송파구 백제고분로 242,1661-9408,무료,"최초30분 무료, 이후 5분당 300원, 저공해차량 50% 할인"
21,구파발광역환승센터 주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,은평구,서울특별시 은평구 진관동 66-30,1661-9408,유료,"1시간 면제, 이후 50% 감면 친환경차 50% 감면"
22,구파발역 환승주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,은평구,"서울특별시 은평구 진관동 66-30 , 지하주차장 1층 20구역",1661-9408,유료,주차비 5분 무료 이후 5분당 50원(친환경차 50% 감면)
23,국립극장,05:00~00:00,환경부(한국자동차환경협회),서울특별시,중구,서울특별시 중구 장충단로 59 국립극장 좌측 출구 주차장,1661-9408,유료,주차요금 별도
24,국방부 서문 주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,용산구,서울특별시 용산구 한강대로 62다길 42,1661-9408,무료,없음
25,국회도서관,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,영등포구,"서울특별시 영등포구 의사당대로1, 국회도서관 앞",1661-9408,유료,없음
26,국회의원회관,09:00 ~ 18:00,환경부(한국자동차환경협회),서울특별시,영등포구,"서울특별시 영등포구 의사당대로1, 국회의원회관 주차장 우측",1661-9408,유료,없음
27,그랜드앰배서더 서울,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,중구,"서울특별시 중구 동호로 287 , 대형버스주차장(장충동2가 186-54)",1661-9408,유료,없음
28,그랜드힐튼호텔,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,서대문구,서울특별시 서대문구 연희로 353,1661-9408,유료,없음
29,난곡동 제1공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,관악구,서울특별시 관악구 난곡로34나길 14 2층,1661-9408,유료,주차요금 별도
30,난향동 주민센터,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,관악구,서울특별시 관악구 난곡로 67,1661-9408,유료,없음
31,남가좌2동 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,서대문구,서울특별시 서대문구 남가좌2동 3-75,1661-9408,무료,5분당 150원
32,냉천길 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강북구,서울특별시 강북구 삼양로 230-12,1661-9408,유료,5분/200원 친환경차 50% 감면
33,노보텔,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 봉은사로 130 지하5층 우측,1661-9408,유료,주차요금 별도
34,노원에코센터,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,노원구,서울특별시 노원구 덕릉로 450 (상계동 770-2),1661-9408,유료,없음
35,노을공원,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,마포구,"서울특별시 마포구 상암동 482-116,",1661-9408,유료,주차비 10분 300원
36,논현로22길 공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 개포로 25길 32,1661-9408,유료,"09:00~19:00 5분당 200원 시간당2,400원 이후시간 무료개방 친환경차 ..."
37,논현초교 공영노외주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,강남구,서울특별시 강남구 강남대로120길 33,1661-9408,무료,5분당300원
38,다락골공영주차장,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,양천구,서울특별시 양천구 중앙로29길 41,1661-9408,무료,5분당 50원
39,당산에스에이치빌 아파트 앞,24시간 이용가능,환경부(한국자동차환경협회),서울특별시,영등포구,서울특별시 영등포구 영신로 183,1661-9408,유료,주차요금 별도

In [33]:
c_df = pd.DataFrame({'이름':charger['c_name'], '구분':charger['typ'], '충전기타입':charger['charge'], '사용중':charger['using'], '급속충전량':charger['amount']})
c_df

                    이름  구분            충전기타입   사용중 급속충전량
0         DMC 산학협력연구센터  급속  DC차데모+AC3상+DC콤보  사용가능   100
1      Park M (주차복합빌딩)  급속             DC콤보   사용중   200
2      Park M (주차복합빌딩)  급속             DC콤보   사용중   200
3                SETEC  급속  DC차데모+AC3상+DC콤보  사용가능   100
4           sh서울주택도시공사  급속             DC콤보   사용중   200
5           sh서울주택도시공사  급속             DC콤보   사용중   200
6        가로공원로 지하공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능    50
7              가양레포츠센터  급속  DC차데모+AC3상+DC콤보  사용가능   100
8            가오리 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능   100
9   강남구청 삼성로 별관 부설 주차장  급속             DC콤보  사용불가   100
10    강남치매지원센터 공영노외주차장  급속             DC콤보  사용가능   200
11    강남치매지원센터 공영노외주차장  급속             DC콤보  사용가능   200
12                강동구청  급속             DC콤보  사용가능   200
13                강동구청  급속             DC콤보  사용가능   200
14            강변 공영주차장  급속             DC콤보  사용가능   200
15            강변 공영주차장  급속             DC콤보  사용가능   200
16         강서구민올림픽체육센터  급속  DC차데모+AC3상+DC콤보   사용중   100
17   개봉1동 주민센터 옆 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능   100
18         개포동공원 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능    50
19            거여동공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능   100
20            곰달래공영주차장  급속             DC콤보   사용중   100
21     곰달래문화복지센터 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능    50
22          공덕1-1공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능    50
23     구로리공원 앞(공중전화부스)  급속  DC차데모+AC3상+DC콤보  사용가능    50
24          구룡공원 공영주차장  급속             DC콤보  사용가능   200
25          구룡공원 공영주차장  급속             DC콤보  사용가능   200
26                구민회관  급속             DC콤보  사용불가   100
27       구파발광역환승센터 주차장  급속             DC콤보  사용불가   200
28       구파발광역환승센터 주차장  급속             DC콤보  사용불가   200
29          구파발역 환승주차장  급속       DC차데모+AC3상  사용가능    50
30          국방부 서문 주차장  급속             DC콤보  사용가능   100
31          그랜드앰배서더 서울  급속  DC차데모+AC3상+DC콤보  사용가능    50
32             그랜드힐튼호텔  급속  DC차데모+AC3상+DC콤보  사용가능    50
33         난곡동 제1공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능    50
34            난향동 주민센터  급속  DC차데모+AC3상+DC콤보  사용가능    50
35         남가좌2동 공영주차장  급속             DC콤보  사용가능   100
36           냉천길 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능   100
37                 노보텔  급속  DC차데모+AC3상+DC콤보  사용가능    50
38              노원에코센터  급속  DC차데모+AC3상+DC콤보  사용가능    50
39                노을공원  급속  DC차데모+AC3상+DC콤보  사용가능    50
40        논현로22길 공영주차장  급속  DC차데모+AC3상+DC콤보  사용가능   100
41        논현초교 공영노외주차장  급속             DC콤보   사용중   200
42        논현초교 공영노외주차장  급속             DC콤보   사용중   200
43            다락골공영주차장  급속             DC콤보  사용가능   100
44      당산에스에이치빌 아파트 앞  급속  DC차데모+AC3상+DC콤보  사용가능    50

In [34]:
len(c_station['name'])

40

In [35]:
len(dic['name'])

NameError: name 'dic' is not defined

In [36]:
import pymysql
# MySQL Connector using pymysql
pymysql.install_as_MySQLdb()
import MySQLdb

In [37]:
conn = pymysql.connect(host='127.0.0.1', user='root', password='1234',
                       db='test', charset='utf8')
cur = conn.cursor()

In [38]:
a=0

In [39]:
tmp_station={}
tmp_charger={}

In [40]:
if a==0:
    tmp_station={'name':[]}
    tmp_charger={'c_name':[]}
    cd=[]

In [201]:
len(dic)

NameError: name 'dic' is not defined

In [45]:
cd=create_date[0:40]
len(cd)

20

In [46]:
len(create_date)
create_date=[]
for i in range(0,40):
    create_date.append('Fri Sep 15 14:59:05 2020')

In [47]:
len(c_station['name'])

40

In [48]:
#충전소
#딕셔너리 for문
for i in range(0,len(charger['c_name'])):
    for j in range(0, len(tmp_station['name'])):
        if len(tmp_station) != 1:
            for t in tmp_station.keys():
                if tmp_station[t][j]!=c_station[t][j]:
                    sql="update charge_station set "+t+"='%s' where "+t+"='%s'"%(t[j], tmp_station[t][j])
                    cur.execute(sql)
            if cd[j]!=create_date[j]:
                sql="update charging_station set create_date='%s' where name='%s'"%(create_date[j], tmp_station['name'][j])
                cur.execute(sql)
    if len(tmp_station['name'])!=len(c_station['name']):
        sql="""insert into charging_station select '%s', '%s', '%s','%s','%s','%s','%s','%s','%s','%s' from dual where not exists (select * from charging_station where name='%s')""" % (c_station['name'][i], c_station['u_time'][i], c_station['agency'][i],c_station['city'][i], c_station['gu'][i], c_station['add'][i], c_station['phone'][i], c_station['fee'][i], c_station['etc'][i], cd[i], c_station['name'][i])
        cur.execute(sql)

IndexError: list index out of range

In [49]:
#select 해서
sql = "select"+t+"from charger"

NameError: name 't' is not defined

In [50]:
#충전기
cid =[]
for i in range(0,len(charger['c_name'])):
    cid.append(i+1)
    tmp_use = {'id':cid, 'name':charger['c_name'], 'c_using':charger['using']}
    for j in range(0, len(tmp_charger['c_name'])):
        if len(tmp_charger) != 1:
            for t in tmp_charger.keys():
                if tmp_charger[t][j]!=charger[t][j]:
                    sql="update charger set "+t+"='%s' where "+t+"='%s'"%(t[j], tmp_charger[t][j])
                    cur.execute(sql)
            #if cd[j]!=create_date[j]:
            #    sql="update charging_station set create_date='%s' where name='%s'"%(create_date[j], dic['name'][j])
            #    cur.execute(sql)
    if len(tmp_charger['c_name'])!=len(charger['c_name']):
        sql="""insert into charger (c_name, typ, charge, c_using, amount, c_create_date) select '%s', '%s', '%s','%s','%s','2020' from dual where not exists (select * from charger where id='%d')""" % (charger['c_name'][i], charger['typ'][i], charger['charge'][i],charger['using'][i],charger['amount'][i], i)
        cur.execute(sql)

OperationalError: (1054, "Unknown column 'c_using' in 'field list'")

In [258]:
conn.commit()

In [48]:
#충전소 그냥 insert
for i in range (0,26):
    sql = "insert into charger (c_name, typ, charge, c_using, amount, c_create_date) values ('%s', '%s', '%s', '%s', '100', '2020')" \
    %(charger['c_name'][i], charger['typ'][i], charger['charge'][i], charger['using'][i])
    
    cur.execute(sql)

In [35]:
#딕셔너리 if문
for i in range(0,len(c_station['name'])):
    for j in range(0, len(dic['name'])):
        if len(dic) != 1:
            if dic['name'][j]!=c_station['name'][j]:
                sql="update charge_station set name='%s' where name='%s'"%(name[j], dic['name'][j])
            if cd[j]!=create_date[j]:
                sql="update charging_station set create_date='%s' where name='%s'"%(cd[j], dic['name'][j])
                cur.execute(sql)
        #위와같은 방식으로 값을 비교하여 다르면 update
    if len(dic['name'])!=len(c_station['name']):
        sql="""insert into charging_station select '%s', '%s', '%s','%s','%s','%s','%s','%s','%s','%s' from dual where not exists (select * from charging_station where name='%s')""" % (c_station['name'][i], c_station['u_time'][i], c_station['agency'][i],c_station['city'][i], c_station['gu'][i], c_station['add'][i], c_station['phone'][i], c_station['fee'][i], c_station['etc'][i], cd[i], c_station['name'][i])
        cur.execute(sql)
        # 중복되지 않는 데이터만 입력하는 sql문이 있는것 같음
    #길이가 다르면 추가 되었다는것

NameError: name 'dic' is not defined

In [36]:
conn.commit()

In [255]:
a=1
tmp_station = c_station
tmp_charger = charger
cd= create_date

In [259]:
tmp_use

{'id': [1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45],
 'name': ['DMC 산학협력연구센터',
  'Park M (주차복합빌딩)',
  'Park M (주차복합빌딩)',
  'SETEC',
  'sh서울주택도시공사',
  'sh서울주택도시공사',
  '가로공원로 지하공영주차장',
  '가양레포츠센터',
  '가오리 공영주차장',
  '강남구청 삼성로 별관 부설 주차장',
  '강남치매지원센터 공영노외주차장',
  '강남치매지원센터 공영노외주차장',
  '강동구청',
  '강동구청',
  '강변 공영주차장',
  '강변 공영주차장',
  '강서구민올림픽체육센터',
  '개봉1동 주민센터 옆 공영주차장',
  '개포동공원 공영주차장',
  '거여동공영주차장',
  '곰달래공영주차장',
  '곰달래문화복지센터 공영주차장',
  '공덕1-1공영주차장',
  '구로리공원 앞(공중전화부스)',
  '구룡공원 공영주차장',
  '구룡공원 공영주차장',
  '구민회관',
  '구파발광역환승센터 주차장',
  '구파발광역환승센터 주차장',
  '구파발역 환승주차장',
  '국방부 서문 주차장',
  '그랜드앰배서더 서울',
  '그랜드힐튼호텔',
  '난곡동 제1공영주차장',
  '난향동 주민센터',
  '남가좌2동 공영주차장',
  '냉천길 공영주차장',
  '노보텔',
  '노원에코센터',
  '노을공원',
  '논현로22길 공영주차장',
  '논현초교 공영노외주차장',
  '논현초교 공영노외주차장',
  '다락골공영주차장',
  '당산에스에이치빌 아파트 앞'],
 'c_using': ['사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용중',
  '사용중',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용중',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용중',
  '사용가능',
  '사용가능',
  '사용중',
  '사용불가',
  '사용불가',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용중',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능',
  '사용가능']}

In [93]:
#요일
str_time = time.ctime()
print(str_time)
print(str_time.split(' ')[0])

AttributeError: 'str' object has no attribute 'ctime'

In [110]:
import time

In [211]:
#날짜
print(time.strftime('%Y-%m-%d') + time.ctime().split(' ')[0])

2020-09-15Tue

In [212]:
#시간
time.strftime('%H:%M:%S')

'00:06:07'

In [ ]:
sql="""insert into usage_status select '%s', '%s', '%s' from dual where not exists (select * from charging_station where id='%d' and start_date='%d' and start_time='%d')""" % (tmp_use['id'][i], date ,u_time, tmp_use['id'][i], date ,u_time)

In [213]:
len(charger['c_name'])

34

In [214]:
len(tmp_use['name'])

34

In [351]:
status=[0]

In [356]:
charger['using'][4]='사용가능'

In [361]:
date=time.strftime('%Y-%m-%d ')+time.ctime().split(' ')[0]
u_time=time.strftime("%H:%M:%S")

for i in range(0,len(tmp_use['name'])):
#    for j in range(0, len(tmp_use['name'])):
    
    if charger['using'][i]=='사용중' and status[i-1]==0:
        date=time.strftime('%Y-%m-%d ')+time.ctime().split(' ')[0]
        u_time=time.strftime("%H:%M:%S")
        sql="""insert into usage_status (id, start_date, start_time) values ('%d', '%s', '%s') """ % (tmp_use['id'][i], date ,u_time)
        cur.execute(sql)
        print(sql)
        status.append(1)
        print(status)
    if charger['using'][i]=='사용가능':
        date=time.strftime('%Y-%m-%d ')+time.ctime().split(' ')[0]
        p_time=time.strftime("%H:%M:%S")
        sql="update usage_status set end_date='%s', end_time='%s', count='%s', use_time='%s' where id='%d' and start_time='%s'"%(date, p_time, '3','3', i+1, tmp_time)
        print(sql)
        cur.execute(sql)
        status.append(0)
        #elif charger['using'][i]=='사용가능' and charge['id']:
        #    sql='update~''

update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='1' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='2' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='3' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='4' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='5' and start_time='01:03:16'
insert into usage_status (id, start_date, start_time) values ('6', '2020-09-15 Tue', '01:03:43')
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='7' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='8' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='9' and start_time='01:03:16'
insert into usage_status (id, start_date, start_time) values ('10', '2020-09-15 Tue', '01:03:43')
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1]
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='11' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='12' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='13' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='14' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='15' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='16' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='17' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='18' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='19' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='20' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='21' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='22' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='23' and start_time='01:03:16'
insert into usage_status (id, start_date, start_time) values ('24', '2020-09-15 Tue', '01:03:43')
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='25' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='26' and start_time='01:03:16'
insert into usage_status (id, start_date, start_time) values ('27', '2020-09-15 Tue', '01:03:43')
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='30' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='31' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='32' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='33' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='34' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='35' and start_time='01:03:16'
insert into usage_status (id, start_date, start_time) values ('36', '2020-09-15 Tue', '01:03:43')
[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='37' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='38' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='39' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='40' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='41' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='42' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='43' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='44' and start_time='01:03:16'
update usage_status set end_date='2020-09-15 Tue', end_time='01:03:43', count='3', use_time='3' where id='45' and start_time='01:03:16'

In [359]:
tmp_time=u_time

In [362]:
conn.commit()